### ISSUE TITLE
How to use in a docker container?

### ISSUE THREAD

**Issue by webtweakers** [adamchainz/django-minify-html#164]
### Not a minify-html bug

- [X] I am not reporting an issue with minification.

### Python Version

3.10.4

### Django Version

4.1.7

### Package Version

1.7.1

### Description

Simple question: how to use this package in a django docker container?

I'm getting this error message, while trying to build:

```
7.749       Checking for Rust toolchain....
7.749
7.749       Cargo, the Rust package manager, is not installed or is not on PATH.
7.749       This package requires Rust and Cargo to compile extensions. Install it through
7.749       the system's package manager or via https://rustup.rs/
```

I'm not sure how to install rust within the docker container.

**Comment by roskakori** [comment]
I used a `Dockerfile` roughly containing, among many other things:
```Dockerfile
# Pull official base image.
FROM --platform=linux/amd64 python:3.12-slim
...

# Install system dependencies.
RUN apt-get update
RUN apt-get install -y cargo  # Needed by minify-html.
...
```
Then, as part of the docker build, it installs cargo and everything that is needed. In the end, in my case this increased the size of the docker tar from 0.9GB to 2.4GB. Also the rust build initially takes a long time. Didn't time it, but must have been around 10 minutes. Probably there's multiple angles to optimize that.

As rust matures and ready-made binaries become more common, this might not be an issue anymore. But right now I question the feasibility of the endeavor.

**Comment by adamchainz** [comment]
This is a minify-html issue, please only report upstream.

The reason you need cargo is because minify-html hasn't shipped Python 3.12 wheels: https://pypi.org/project/minify-html/#files . I suggest you make a PR upstream adding Python 3.12 to the matrix.

**Comment by webtweakers** [comment]
Alright, thanks for the feedback, though!

**Comment by roskakori** [comment]
@adamchainz  Thanks for your research. As suggested I added a PR: https://github.com/wilsonzlin/minify-html/pull/163.
