### ISSUE TITLE
Breaks django.contrib.admin UI

### ISSUE THREAD

**Issue by rphlo** [adamchainz/django-minify-html#165]
### Not a minify-html bug

- [X] I am not reporting an issue with minification.

### Description

I have been using the django-minify middleware and it breaks some UI elements in django's shipped admin by stripping some default attributes, for example removing `type="text"` on inputs see https://code.djangoproject.com/ticket/34999 .
This is explained clearly in minify-html repo and I understand the logic (e.g: you need to have CSS rule stating `input:not([type]), input[type=text]` instead of just `input[type=text]`). Problem is that django repo CSS rules doesn't take those cases in account.
I know that this repo owner @adamchainz is also a member of Django project steering council.
So here is my question, what would be the recommended way to proceed with this, should I create a issue/PR for django even though it affect only user using minify-html, should I create a fix within this repo, or should I limit my fix to my own project and let other users to figure out the issue/fix by themselves?

**Comment by adamchainz** [comment]
Make a ticket in Django. IMO it would be acceptable as there are many ways to apply HTML minification, such as on CDNs, where this issue may also arise.
