### ISSUE TITLE
<head> tag

### ISSUE THREAD

**Issue by russian-master** [adamchainz/django-minify-html#168]
### Not a minify-html bug

- [X] I am not reporting an issue with minification.

### Django Version

4.1.7

### Package Version

1.5.0

### Description

I'm not sure if it is related to minify-html or to django-minify-html.
However it cuts off the head tag, this behavior is rather strange and can potentially break the layout or some services processing. 
If removing ` <head></head>` is default for minify-html I'd like to have some settings in django to prevent this.

**Comment by adamchainz** [comment]
This is a minify-html issue and could be reported there, but provide concrete information about how it can “break the layout”. minify-html doesn’t care about non-browser services, so that’s unlikely to hold sway there.

We can’t add anything in this package to prevent that behaviour.
