### ISSUE TITLE
Update README: Cloudflare has deprecated Auto Minify

### ISSUE THREAD

**Issue by Jer-Pha** [adamchainz/django-minify-html#197]
### Not a minify-html bug

- [X] I am not reporting an issue with minification.

### Description

Cloudflare has deprecated Auto Minify and should no longer be referenced in the [README](https://github.com/adamchainz/django-minify-html/blob/51f3414ccb1d97cda2bc333b416a8447f8330053/README.rst?plain=1#L153). 

![image](https://github.com/adamchainz/django-minify-html/assets/131234246/3f50a198-9a7f-4855-bb13-46ad807807ca)

**Comment by adamchainz** [comment]
Sure, I guess. I won't get round to this for a while though.
