### ISSUE TITLE
Some issues I found

### ISSUE THREAD

**Issue by shawnngtq** [adamchainz/django-minify-html#24]
### Python Version

3.10.2

### Django Version

4.0.2

### Package Version

1.0.0

### Description

I discover 2 issues

## Break html output

Using only the installation settings: https://github.com/adamchainz/django-minify-html#installation

With this enabled

![image](https://user-images.githubusercontent.com/19720783/156906770-405524db-60cf-4b4a-81c2-6d6bef08f3b8.png)

Without this, the original:

![image](https://user-images.githubusercontent.com/19720783/156906834-a292a4b2-c207-4c56-aadb-f7b0491b5810.png)

## Break select option with empty value

https://github.com/django-crispy-forms/crispy-bootstrap5/issues/96

This issue is already reported: https://github.com/adamchainz/django-minify-html/issues/21

Reporting this as I have to disabled it because I can't live with these 2 issues. Hope to use this library if I could 😁

**Comment by adamchainz** [comment]
> Break html output

Please narrow this down to the problematic HTML - a screenshot is no use. Also there's not much I can do for broken minimization apart from report it upstream so please consider doing that.

You can also try disabling features with `minify_args` and see if that fixes things.

**Comment by shawnngtq** [comment]
Yup, I can wait for upstream fix that. Since you are aware, I will close this issue now. Thanks!

**Comment by adamchainz** [comment]
Are you reporting upstream? I'd be interested in getting a link

**Comment by shawnngtq** [comment]
I don't, they probably will ask for actual html etc. Right now I am overwhelm by my project's tasks. When I need this for speed optimization, I might raise then. Will post if I do 😄

**Comment by adamchainz** [comment]
If you need to optimize your site, it's much more important to ensure you have compression (gzip/brotli), and a CDN. HTML minification for like a 1-3% improvement on top.

**Comment by shawnngtq** [comment]
I see, right now I am just using AWS cloudfront, in terms of infra side, I trust AWS to be able to perform. Right now my focus is to build the essential features and get audience. Optimization is at the bottom of my todo. By the time I need it, Upstream might already fixed it.

Thanks for the advise!
