### ISSUE TITLE
Issue installing it on Alpine image

### ISSUE THREAD

**Issue by kennylajara** [adamchainz/django-minify-html#26]
### Python Version

3.10.2

### Django Version

4.0.2

### Package Version

1.0.0

### Description

I am creating the docker image of my app (I was developing it with `python manage.py run server`) and I want to use an alpine image, but I get this error message when I run `pip install -r requirements.txt`:

```
ERROR: Could not find a version that satisfies the requirement minify-html (from django-minify-html) (from versions: none)
ERROR: No matching distribution found for minify-html
```

**Comment by adamchainz** [comment]
This is an issue for upstream: https://github.com/wilsonzlin/minify-html

I will just say though, using Alpine for Python is normally a mistake, see https://pythonspeed.com/articles/alpine-docker-python/ and https://pythonspeed.com/articles/faster-python/ .
