### ISSUE TITLE
Enabling MinifyHtmlMiddleware causes infinite loop

### ISSUE THREAD

**Issue by kevin-olbrich** [adamchainz/django-minify-html#48]
### Python Version

3.9.2

### Django Version

3.2.13

### Package Version

1.3.0

### Description

Hi!

I've added MinifyHtmlMiddleware to my project but rendering a view results in an infinite loop until the browser times out.
This only happens on a Debian 11 machine with uWSGI. Running the same project on Windows 11 works and the module works correctly.

```
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.gzip.GZipMiddleware",
    "django_minify_html.middleware.MinifyHtmlMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "user_sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "corsheaders.middleware.CorsPostCsrfMiddleware",
    "x_forwarded_for.middleware.XForwardedForMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.contrib.sites.middleware.CurrentSiteMiddleware",
]
```

Even with GZipMiddleware and CorsMiddleware disabled, the same issue is present.

What could be the cause for this? The application does not crash and does not log anything.

**Comment by kevin-olbrich** [comment]
Ok, using a custom middleware and disabling both "minify_css" and "minify_js", the side loads and minifies html.
What can cause this to fail on debian and make it work on windows at the same time? I tried building the package myself using "pip3 install --upgrade --no-binary :all: django-minify-html" which did not help.
Could this be a dependency problem on system libraries?

**Comment by adamchainz** [comment]
minify-html just released a new version with different CSS and JS minifiers: https://github.com/wilsonzlin/minify-html/blob/master/CHANGELOG.md

Tyr that out.

**Comment by adamchainz** [comment]
Gonna mark this as closed since it's really an upstream issue and recent work has been done to fix it.

Please report in minify-html if you are still having problems, but you can ping me.

**Comment by adamchainz** [comment]
Thanks for your support 🙏🏻
