### ISSUE TITLE
ending body & html tag missing

### ISSUE THREAD

**Issue by amanrawat121** [adamchainz/django-minify-html#75]
### Python Version

3.10

### Django Version

4.1.2

### Package Version

1.3.0

### Description

ending </body> and </html tags are missing, posting screenshots here...
![image](https://user-images.githubusercontent.com/90174212/197526066-c0f55e4f-43ff-4ef5-8500-7f54e7eeb1eb.png)
Please reply...

**Comment by adamchainz** [comment]
This is legitimate HTML and deliberately done by minify-html: https://github.com/wilsonzlin/minify-html#tags

**Comment by amanrawat121** [comment]
Thanks for responding.. I got it
